stt4-frontend-chart:
  image:
    repository: artifactory.dagility.com/docker/stt4-frontend
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: stt4-frontend-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false

stt4-backend-chart:
  image:
    repository: artifactory.dagility.com/docker/stt4-backend
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: stt4-backend-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false
